name: ah_mobile
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http:
  provider:
  validators:
  image_picker:
  video_player:
  image_cropper:
  percent_indicator: "^2.1.1"
  tuple: ^1.0.3
  basic_utils: ^2.4.8

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
  - images/
  - config/

  fonts:
    - family: Inika
      fonts:
        - asset: fonts/Inika/Inika-Regular.ttf
        - asset: fonts/Inika/Inika-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Regular.ttf
        - asset: fonts/Poppins/Poppins-Thin.ttf
        - asset: fonts/Poppins/Poppins-Light.ttf
        - asset: fonts/Poppins/Poppins-Thin.ttf
          weight: 700
